### ISSUE TITLE
Uncaught UnboundLocalError: local variable 'transparency' referenced before assignment


### ISSUE THREAD

**Issue by UrbanPlan-LDB** [paolomartinis/transparency_setter#3]
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\transparency_setter\transparency_setter.py", line 296, in update_slider_from_selected_layer
    self.update_slider_from_layer_node(selected_layer_node)
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\transparency_setter\transparency_setter.py", line 315, in update_slider_from_layer_node
    rounded_transparency = round(transparency)
UnboundLocalError: local variable 'transparency' referenced before assignment

```
transparency_setter 0.2, QGIS 3.28.6-Firenze on Windows 10

**Comment by paolomartinis** [comment]
I can't reproduce it. Can you give me more context?
I think a screenshot of the Layers Panel (with the tree fully expanded) just before the exception arises will suffice.
